apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: address-book-argo-application
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: http://gitlab.oggdossev.com/address-book/address-book-config
    targetRevision: HEAD
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: address-book-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
