apiVersion: v1
kind: Service
metadata:
  name: address-book-backend
  labels:
    app: address-book
spec:
  ports:
    - port: 9000
  selector:
    app: address-book
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book
  labels:
    app: address-book
spec:
  selector:
    matchLabels:
      app: address-book
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: address-book
        tier: backend
    spec:
      containers:
      - image: ognyandossev/demo-app:backend-171
        name: address-book
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: database-pass
              key: password
        - name: DB_SERVER
          value: address-book-database
        - name: DB_USER
          value: root
        - name: DB_NAME
          value: address_book
        - name: SITE_URL
          value: http://localhost/
        ports:
        - containerPort: 9000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: address-book-backend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: address-book-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

