apiVersion: v1
kind: Service
metadata:
  name: address-book-frontend
  labels:
    app: address-book
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: address-book
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book-frontend
  labels:
    app: address-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-book
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: address-book
        tier: frontend
    spec:
      containers:
      - image: ognyandossev/demo-app:frontend-171
        name: address-book-frontend
        env:
        - name: FRONTEND_PORT
          value: "80"
        - name: BACKEND_HOST
          value: address-book-backend
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: address-book-frontend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: address-book-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

