apiVersion: v1
kind: Service
metadata:
  name: address-book-database
  labels:
    app: address-book
spec:
  ports:
    - port: 3306
  selector:
    app: address-book
    tier: database
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book-database
  labels:
    app: address-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-book
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: address-book
        tier: database
    spec:
      containers:
      - image: ognyandossev/demo-app:database-171
        name: database
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: database-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: database-persistent-storage
        persistentVolumeClaim:
          claimName: database-pv-claim
---
#
# PersistentVolumeClaim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

